name: cloudformatious
description: Apply a CloudFormation template using cloudformatious
inputs:
  version:
    description: |
      The version of cloudformatious-cli to install (default: latest).

      See https://github.com/connec/cloudformatious-cli/releases.
    default: latest
  operation:
    description: |
      The operation to perform.

      Options:
      - apply-stack (default)
      - install
    default: apply-stack
  stack-name:
    description: |
      The name that is associated with the stack

      Required if `operation` is `apply-stack`.
  template-path:
    description: |
      Path to the template to be applied

      Required if `operation` is `apply-stack`.
  capabilities:
    description: Capabilities to explicitly acknowledge
  client-request-token:
    description: A unique identifier for this `apply_stack` operation
  notification-arns:
    description: The Simple Notification Service (SNS) topic ARNs to publish stack related events
  package-bucket:
    description: |
      The S3 bucket to upload packages to.

      Required if there are references to local paths in the template.
  package-prefix:
    description: A prefix for any uploaded packages
  parameters:
    description: A list of input parameters for the stack
  resource-types:
    description: The template resource types that you have permissions to work with for this `apply_stack` operation, such as `AWS::EC2::Instance`, `AWS::EC2::*`, or `Custom::MyCustomInstance`
  role-arn:
    description: The Amazon Resource Name (ARN) of an AWS Identity And Access Management (IAM) role that AWS CloudFormation assumes to apply the stack
  tags:
    description: |
      Key-value pairs to associate with this stack.

      Tags should be supplied either as `key=value` strings and/or as a JSON object (e.g. `{"key1": "value1", "key2": "value2"}`).
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node20"
  main: "dist/index.js"
